name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
  - assets/images/black_and_green_flat_illustrated_organic_cosmetics_logo_1.png
  - assets/images/image_6.png
  - assets/images/element_5_digital_cp_bbsda_2_eri_unsplash_2.png
  - assets/vectors/vector_1_x2.svg
  - assets/images/left_arrow_2.png
  - assets/images/beautiful_female_with_shopping_cart_walking_by_supermarket_freezer_choosing_what_buy_11.png
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/group_6_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/images/left_arrow_1.png
  - assets/images/beautiful_female_with_shopping_cart_walking_by_supermarket_freezer_choosing_what_buy_1.png
  - assets/vectors/group_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/vector_57_stroke_x2.svg
  - assets/images/black_and_green_flat_illustrated_organic_cosmetics_logo_1.png
  - assets/images/slider_74_removebg_preview_1.png
  - assets/images/slider_74_removebg_preview_12.png
  - assets/images/element_5_digital_cp_bbsda_2_eri_unsplash.png
  - assets/images/element_5_digital_cp_bbsda_2_eri_unsplash1.png
  - assets/vectors/vector_11_x2.svg
  - assets/images/element_5_digital_cp_bbsda_2_eri_unsplash_1.png
  - assets/vectors/vector_12_x2.svg

